In [1]:
import pandas as pd
import numpy as np

### 퍼셉트론
- 2차원 데이터가 기본이다. (스칼라, 벡터, 매트릭스, 텐서), 차원이 있는 데이터를 기본으로 다룬다.

In [5]:
# 입력: 시험 성적, 출석률
x = np.array([85,90])
w = np.array([0.7, 0.3])
b = -50
z = np.dot(x,w) + b
y = 1 if z > 0 else 0


In [7]:
print('가중합:', z)
print('출력 y:', y)

가중합: 36.499999999999986
출력 y: 1


### MLP
#### 활성화 함수
- 시그모이드 : 0 - 1 사이의 확률을 구하는 공식
- RELU : 입력값이 0 보다 작으면 0, 0보다 크면 입력값
#### 손실 함수
- MSE : 예측(회귀)
- CrossEntropy : 분류


In [2]:
# MSE
y_true = np.array([1.0, 0.0, 1.0])
y_pred = np.array([0.9, 0.2, 0.8])

mse = np.mean((y_true - y_pred)**2)
print('MSE = ', mse)


MSE =  0.029999999999999995


In [ ]:
# CrossEntropy (확률 분포의 차이)
y_true = np.array([1.0, 0.0, 1.0])
y_pred = np.array([0.9, 0.2, 0.8])

ce = -np.sum(y_true * np.log(y_pred + 1e-9))
print('ce =',ce)

ce = 0.32850406461092496


In [ ]:
# 경사하강법 (w와 b 최적화 과정)
def gd(lr, steps=20):
    w = 5.0 # 시작점
    history = [w]
    for _ in range(steps):
        grad = 2*w # f(W) = w^2
        w = w - lr*grad
        history.append(w)
    return history

for lr in [0.05,0.3,1.1]:
    h = gd(lr)
    print(h)

# 빨리 학습시키려고 학습률을 크게 주면 오히려 오차가 커짐 

[5.0, 4.5, 4.05, 3.6449999999999996, 3.2804999999999995, 2.95245, 2.657205, 2.3914845, 2.1523360499999997, 1.9371024449999998, 1.7433922004999998, 1.5690529804499997, 1.4121476824049997, 1.2709329141644996, 1.1438396227480496, 1.0294556604732445, 0.9265100944259201, 0.8338590849833281, 0.7504731764849952, 0.6754258588364956, 0.607883272952846]
[5.0, 2.0, 0.8, 0.32000000000000006, 0.12800000000000003, 0.05120000000000001, 0.020480000000000005, 0.008192000000000003, 0.0032768000000000016, 0.001310720000000001, 0.0005242880000000004, 0.00020971520000000014, 8.388608000000006e-05, 3.3554432000000026e-05, 1.342177280000001e-05, 5.368709120000004e-06, 2.147483648000002e-06, 8.589934592000008e-07, 3.435973836800004e-07, 1.3743895347200017e-07, 5.4975581388800065e-08]
[5.0, -6.0, 7.200000000000001, -8.640000000000002, 10.368000000000004, -12.441600000000006, 14.929920000000012, -17.91590400000002, 21.499084800000027, -25.798901760000035, 30.958682112000048, -37.15041853440006, 44.5805022412800

In [11]:
# MLP : XOR
np.random.seed(0)
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])
w1 = np.random.randn(2, 4) * 0.5
b1 = np.zeros((1, 4))
w2 = np.random.randn(4, 1) * 0.5
b2 = np.zeros((1, 1))
w1, b1, w2, b2

(array([[ 0.88202617,  0.2000786 ,  0.48936899,  1.1204466 ],
        [ 0.933779  , -0.48863894,  0.47504421, -0.0756786 ]]),
 array([[0., 0., 0., 0.]]),
 array([[-0.05160943],
        [ 0.20529925],
        [ 0.07202179],
        [ 0.72713675]]),
 array([[0.]]))

In [12]:
# 오차함수
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [13]:
h = sigmoid(X @ w1 + b1)
y_pred = (h @ w2 + b2)
print('초기 예측:',y_pred.ravel().round(3))

초기 예측: [0.476 0.435 0.669 0.634]
